from snakemake.utils import min_version
min_version("8.20.6")

configfile: "config/config.yaml"
report: "report/workflow.rst"
# container: "docker://continuumio/miniconda3"
container: "./singularity/miniconda3.sif"

# include
include: "rules/common.smk"
include: "rules/miscellaneous.smk"
include: "rules/download.smk"
include: "rules/process.smk"

rule all:
    input: get_run_all
    default_target: True
