# genome url, must be .2bit
genome_url: "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.2bit"
# rmsk used as black list
rmsk_url: "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/rmsk.txt.gz"
# https://deeptools.readthedocs.io/en/latest/content/feature/effectiveGenomeSize.html
effectiveGenomeSize: 2308125299
fragmentLength: 150
binSize: 50
sampleSize: 50000000
regionSize: 300